#!/bin/bash
#SBATCH -J get_features          # job name to display in squeue
#SBATCH -o get_features.txt       # standard output file
#SBATCH -p standard-s    # requested partition
#SBATCH --exclusive      # do not share nodes
#SBATCH --mem 256GB
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

# load any modules you need and/or activate conda environments
# run python script

python get_features.py 0 1
